// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	UserID     pgtype.UUID     `db:"user_id" json:"user_id"`
	Action     string          `db:"action" json:"action"`
	EntityType string          `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID     `db:"entity_id" json:"entity_id"`
	OldValues  json.RawMessage `db:"old_values" json:"old_values"`
	NewValues  json.RawMessage `db:"new_values" json:"new_values"`
	IpAddress  string          `db:"ip_address" json:"ip_address"`
	UserAgent  pgtype.Text     `db:"user_agent" json:"user_agent"`
	CreatedAt  sql.NullTime    `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt sql.NullTime       `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt sql.NullTime       `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	UserID    uuid.UUID    `db:"user_id" json:"user_id"`
	TokenHash string       `db:"token_hash" json:"token_hash"`
	UserAgent pgtype.Text  `db:"user_agent" json:"user_agent"`
	IpAddress string       `db:"ip_address" json:"ip_address"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	Name            pgtype.Text        `db:"name" json:"name"`
	PasswordHash    string             `db:"password_hash" json:"password_hash"`
	Role            string             `db:"role" json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	CreatedAt       sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime       `db:"updated_at" json:"updated_at"`
}
