// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	// Audit log queries
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// Refresh token queries
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Session queries
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]*AuditLog, error)
	GetRefreshToken(ctx context.Context, id uuid.UUID) (*RefreshToken, error)
	GetSessionByToken(ctx context.Context, tokenHash string) (*Session, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UserExists(ctx context.Context, email string) (bool, error)
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
